#!/usr/bin/env bash
#
# Bash CLI Framework
# Version: 1.0.0
# Description: Rust CLI
# Repository: https://github.com/modufolio/bash-cli
#
# This file is auto-generated from modular source files.
# Do not edit this file directly. Edit files in src/ and run build.sh
#
# Generated: 2026-05-22 10:57:27 UTC
#


# ============================================================================
# Module: 00.header/init.sh
# ============================================================================

#!/usr/bin/env bash

set -euo pipefail

# Require bash >= 4 (needed for `declare -A` and `mapfile`).
# macOS ships bash 3.2 — install a newer one via `brew install bash`.
if (( BASH_VERSINFO[0] < 4 )); then
    cat >&2 <<EOF
Error: cli.sh requires bash >= 4 (you have ${BASH_VERSION}).

On macOS, install a newer bash:
    brew install bash

Then put the Homebrew bash earlier on your PATH so '/usr/bin/env bash'
resolves to it.
EOF
    exit 1
fi

# ============================================================================
# Module: 01.config/colors.sh
# ============================================================================

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly BLUE='\033[0;34m'
readonly PURPLE='\033[0;35m'
readonly CYAN='\033[0;36m'
readonly WHITE='\033[0;37m'
readonly BOLD='\033[1m'
readonly NC='\033[0m' # No Color

# ============================================================================
# Module: 01.config/globals.sh
# ============================================================================

# Global variables
declare -A COMMANDS
declare -A COMMAND_DESCRIPTIONS
declare -A COMMAND_USAGE
declare -A COMMAND_EXAMPLES
declare -A COMMAND_TAGS

# Add a cache for plugin commands and aliases
declare -A PLUGIN_COMMANDS
declare -A COMMAND_ALIASES
declare -A COMMAND_GROUPS  # New: store commands by group

# Test framework globals
declare -i TESTS_TOTAL=0
declare -i TESTS_PASSED=0
declare -i TESTS_FAILED=0
TEST_DIR=""
PLUGIN_DIR=""

# Global for test storage
declare -A TESTS
declare -A TEST_DESCRIPTIONS
declare -A TEST_TAGS

# ============================================================================
# Module: 01.config/metadata.sh
# ============================================================================

CLI_NAME="$(basename "$0")"
CLI_VERSION="1.0.0"
CLI_DESCRIPTION="Rust CLI"

# ============================================================================
# Module: 01.config/env.sh
# ============================================================================


# Dotenv loader for bash-cli
# Inspired by Symfony\Component\Dotenv
# Loads environment variables from .env files

# Regex pattern for valid variable names (matching Symfony's VARNAME_REGEX)
readonly ENV_VARNAME_REGEX='^[a-zA-Z_][a-zA-Z0-9_]*$'

# Track which variables were loaded by dotenv
declare -g DOTENV_VARS=""

# Parse a single line from .env file
# Arguments:
#   $1 - line: The line to parse
#   $2 - override: Whether to override existing variables (default: false)
parse_env_line() {
    local line="$1"
    local override="${2:-false}"
    local name value

    # Skip empty lines
    [[ -z "$line" ]] && return 0

    # Skip comments
    [[ "$line" =~ ^[[:space:]]*# ]] && return 0

    # Remove 'export ' prefix if present
    line="${line#export }"
    line="${line#export	}"  # Also handle tab

    # Check if line contains '='
    if [[ ! "$line" =~ = ]]; then
        return 0
    fi

    # Split on first '='
    name="${line%%=*}"
    value="${line#*=}"

    # Trim whitespace from name
    name="${name#"${name%%[![:space:]]*}"}"
    name="${name%"${name##*[![:space:]]}"}"

    # Validate variable name
    if [[ ! "$name" =~ $ENV_VARNAME_REGEX ]]; then
        return 0
    fi

    # Process the value
    value=$(parse_env_value "$value")

    # Check if variable already exists and was NOT loaded by dotenv
    # Variables loaded by dotenv can be overridden by subsequent .env files
    if [[ -n "${!name+x}" ]] && [[ "$override" != "true" ]]; then
        # Check if this variable was loaded by dotenv
        local is_dotenv_var=false
        if [[ -n "$DOTENV_VARS" ]]; then
            IFS=',' read -ra loaded_vars <<< "$DOTENV_VARS"
            for loaded_var in "${loaded_vars[@]}"; do
                if [[ "$loaded_var" == "$name" ]]; then
                    is_dotenv_var=true
                    break
                fi
            done
        fi

        # If not a dotenv var, skip (don't override system variables)
        if [[ "$is_dotenv_var" != "true" ]]; then
            return 0
        fi
    fi

    # Export the variable
    export "$name=$value"

    # Track loaded variable (add if not already tracked)
    if [[ "$DOTENV_VARS" == "" ]]; then
        DOTENV_VARS="$name"
    elif [[ ",$DOTENV_VARS," != *",$name,"* ]]; then
        DOTENV_VARS="$DOTENV_VARS,$name"
    fi
}

# Parse environment variable value
# Handles quoted strings, variable expansion, and special characters
# Arguments:
#   $1 - value: The value to parse
parse_env_value() {
    local value="$1"
    local result=""

    # Trim leading/trailing whitespace
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"

    # Handle single-quoted strings (no variable expansion)
    if [[ "$value" =~ ^\'.*\'$ ]]; then
        # Remove surrounding single quotes
        value="${value#\'}"
        value="${value%\'}"
        echo "$value"
        return 0
    fi

    # Handle double-quoted strings (with variable expansion)
    if [[ "$value" =~ ^\".*\"$ ]]; then
        # Remove surrounding double quotes
        value="${value#\"}"
        value="${value%\"}"

        # Expand variables within double quotes
        value=$(expand_env_variables "$value")

        # Handle escape sequences
        value="${value//\\n/$'\n'}"
        value="${value//\\r/$'\r'}"
        value="${value//\\t/$'\t'}"
        value="${value//\\\"/\"}"
        value="${value//\\\\/\\}"

        echo "$value"
        return 0
    fi

    # Handle unquoted values
    # Remove inline comments (not within quotes)
    if [[ "$value" =~ ^([^#]*[^[:space:]])([[:space:]]+#.*)$ ]]; then
        value="${BASH_REMATCH[1]}"
    fi

    # Expand variables in unquoted values
    value=$(expand_env_variables "$value")

    echo "$value"
}

# Expand environment variables in a string
# Supports: $VAR, ${VAR}, ${VAR:-default}, ${VAR:=default}
# Arguments:
#   $1 - text: The text containing variables to expand
expand_env_variables() {
    local text="$1"
    local result=""
    local pos=0
    local len="${#text}"

    while [[ $pos -lt $len ]]; do
        # Find next variable reference
        local remaining="${text:$pos}"

        # Match ${VAR:-default}, ${VAR:=default}, ${VAR}, or $VAR
        if [[ "$remaining" =~ ^\$\{([a-zA-Z_][a-zA-Z0-9_]*)(:-([^}]*))?\} ]]; then
            # Matched ${VAR} or ${VAR:-default}
            local var_name="${BASH_REMATCH[1]}"
            local has_default="${BASH_REMATCH[2]}"
            local default_value="${BASH_REMATCH[3]}"
            local match_len="${#BASH_REMATCH[0]}"

            # Get variable value using indirect expansion (safe for unset vars)
            local var_value=""
            if [[ -v "$var_name" ]]; then
                var_value="${!var_name}"
            fi

            # Apply default if variable is unset or empty
            if [[ -z "$var_value" && -n "$has_default" ]]; then
                var_value="$default_value"
            fi

            result+="$var_value"
            pos=$((pos + match_len))

        elif [[ "$remaining" =~ ^\$\{([a-zA-Z_][a-zA-Z0-9_]*):=([^}]*)\} ]]; then
            # Matched ${VAR:=default} - set variable if unset
            local var_name="${BASH_REMATCH[1]}"
            local default_value="${BASH_REMATCH[2]}"
            local match_len="${#BASH_REMATCH[0]}"

            # Get or set variable value (safe for unset vars)
            local var_value=""
            if [[ -v "$var_name" ]]; then
                var_value="${!var_name}"
            fi
            if [[ -z "$var_value" ]]; then
                export "$var_name=$default_value"
                var_value="$default_value"
            fi

            result+="$var_value"
            pos=$((pos + match_len))

        elif [[ "$remaining" =~ ^\$([a-zA-Z_][a-zA-Z0-9_]*) ]]; then
            # Matched $VAR (without braces)
            local var_name="${BASH_REMATCH[1]}"
            local match_len="${#BASH_REMATCH[0]}"

            # Get variable value using indirect expansion (safe for unset vars)
            local var_value=""
            if [[ -v "$var_name" ]]; then
                var_value="${!var_name}"
            fi
            result+="$var_value"
            pos=$((pos + match_len))

        else
            # No variable found, copy one character
            result+="${text:$pos:1}"
            pos=$((pos + 1))
        fi
    done

    echo "$result"
}

# Load environment variables from a .env file
# Arguments:
#   $1 - file_path: Path to the .env file
#   $2 - override: Whether to override existing variables (default: false)
load_env_from_file() {
    local file_path="$1"
    local override="${2:-false}"
    local line

    # Check if file exists and is readable
    if [[ ! -f "$file_path" ]] || [[ ! -r "$file_path" ]]; then
        return 0
    fi

    # Check for BOM (Byte Order Mark) - not supported
    if [[ -f "$file_path" ]]; then
        local first_bytes
        first_bytes=$(head -c 3 "$file_path" | od -An -tx1 | tr -d ' \n')
        if [[ "$first_bytes" == "efbbbf" ]]; then
            error "Loading files starting with a byte-order-mark (BOM) is not supported: $file_path"
            return 1
        fi
    fi

    # Read file line by line
    while IFS= read -r line || [[ -n "$line" ]]; do
        parse_env_line "$line" "$override"
    done < "$file_path"

    return 0
}

# Load .env files with environment-specific variants
# Loads in order: .env, .env.local, .env.$env, .env.$env.local
# Arguments:
#   $1 - base_path: Base path for .env files (default: project root)
#   $2 - env: Environment name (e.g., dev, prod, test) - optional
#   $3 - override: Whether to override existing variables (default: false)
load_env() {
    local base_path="${1:-.}"
    local env="${2:-}"
    local override="${3:-false}"
    local env_file

    # Ensure base_path is absolute
    if [[ ! "$base_path" =~ ^/ ]]; then
        base_path="$(cd "$base_path" 2>/dev/null && pwd)" || base_path="."
    fi

    # Load main .env file (or .env.dist as fallback)
    env_file="$base_path/.env"
    if [[ -f "$env_file" ]]; then
        load_env_from_file "$env_file" "$override"
    elif [[ -f "$base_path/.env.dist" ]]; then
        load_env_from_file "$base_path/.env.dist" "$override"
    fi

    # Determine environment if not specified
    if [[ -z "$env" ]]; then
        env="${APP_ENV:-${CLI_ENV:-dev}}"
    fi

    # Load .env.local (skip in test environment - tests should be consistent)
    if [[ "$env" != "test" ]] && [[ -f "$base_path/.env.local" ]]; then
        load_env_from_file "$base_path/.env.local" "$override"
        # Update env in case it was overridden
        env="${APP_ENV:-${CLI_ENV:-$env}}"
    fi

    # Skip environment-specific files if env is 'local'
    if [[ "$env" == "local" ]]; then
        return 0
    fi

    # Load environment-specific .env file
    if [[ -n "$env" ]] && [[ -f "$base_path/.env.$env" ]]; then
        load_env_from_file "$base_path/.env.$env" "$override"
    fi

    # Load environment-specific local .env file
    if [[ -n "$env" ]] && [[ -f "$base_path/.env.$env.local" ]]; then
        load_env_from_file "$base_path/.env.$env.local" "$override"
    fi

    # Export DOTENV_VARS for tracking
    export DOTENV_VARS

    return 0
}

# Load .env files with override enabled
# Arguments:
#   $1 - base_path: Base path for .env files (default: project root)
#   $2 - env: Environment name (optional)
overload_env() {
    load_env "$1" "$2" "true"
}

# Get the project root directory (where .env files should be located)
get_env_project_root() {
    # Try to use get_project_root if available (from loader.sh)
    if declare -f get_project_root > /dev/null 2>&1; then
        get_project_root
    elif declare -f get_script_dir > /dev/null 2>&1; then
        local script_dir
        script_dir=$(get_script_dir)
        # If we're in dist/, go up one level
        if [[ "$(basename "$script_dir")" == "dist" ]]; then
            dirname "$script_dir"
        else
            echo "$script_dir"
        fi
    else
        # Fallback: use current directory
        pwd
    fi
}

# ============================================================================
# Module: 02.utils/helpers.sh
# ============================================================================

# Helper to generate alias (e.g., docker:images -> d:i)
generate_alias() {
    local cmd="$1"
    local alias=""
    IFS=':' read -ra parts <<< "$cmd"
    for part in "${parts[@]}"; do
        alias+="${part:0:1}:"
    done
    alias="${alias%:}"
    echo "$alias"
}

# Get the directory of this script (even if symlinked)
get_script_dir() {
    local SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do
        DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    done
    DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
    echo "$DIR"
}

# ============================================================================
# Module: 02.utils/output.sh
# ============================================================================

# Colored output functions
error()   { echo -e "${RED}[ERROR]${NC} $1" >&2; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
debug()   { echo -e "${PURPLE}[DEBUG]${NC} $1"; }
test_info() { echo -e "${BLUE}[TEST] $1"; }
test_pass() { echo -e "${GREEN}✓${NC} $1"; ((++TESTS_PASSED)); ((++TESTS_TOTAL)); }
test_fail() { echo -e "${RED}[FAIL]${NC} $1" >&2; ((++TESTS_FAILED)); ((++TESTS_TOTAL)); }
test_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
check() { echo -e "${GREEN}✓${NC} $1"; }

line() {
    printf "\n"
}

# ============================================================================
# Module: 02.utils/progress.sh
# ============================================================================

# Progress bar
show_progress() {
    local current=$1
    local total=$2
    local width=40
    local percentage=$((current * 100 / total))
    local completed=$((current * width / total))
    local remaining=$((width - completed))

    printf "\r${BLUE}Progress: [${GREEN}"
    printf "%0.s█" $(seq 1 $completed)
    printf "${NC}"
    printf "%0.s▒" $(seq 1 $remaining)
    printf "${BLUE}] %d%% (%d/%d)${NC}" $percentage $current $total

    if [ $current -eq $total ]; then
        echo
    fi
}

# ============================================================================
# Module: 02.utils/table.sh
# ============================================================================

# Table rendering
print_table() {
    local -n headers=$1
    local -n rows=$2
    local -a widths

    for i in "${!headers[@]}"; do
        widths[$i]=${#headers[$i]}
        for row in "${rows[@]}"; do
            IFS='|' read -ra cols <<< "$row"
            if [[ ${#cols[$i]} -gt ${widths[$i]} ]]; then
                widths[$i]=${#cols[$i]}
            fi
        done
    done

    printf "${BOLD}"
    for i in "${!headers[@]}"; do
        printf "%-*s  " "${widths[$i]}" "${headers[$i]}"
    done
    printf "${NC}\n"

    for i in "${!headers[@]}"; do
        printf "%-*s  " "${widths[$i]}" "$(printf -- '-%.0s' $(seq 1 ${widths[$i]}))"
    done
    echo

    for row in "${rows[@]}"; do
        IFS='|' read -ra cols <<< "$row"
        for i in "${!cols[@]}"; do
            printf "%-*s  " "${widths[$i]}" "${cols[$i]}"
        done
        echo
    done
}

# ============================================================================
# Module: 03.core/parser.sh
# ============================================================================

# Argument parser
parse_arguments() {
    local -n parsed_args=$1
    shift

    parsed_args["_positional"]=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --*=*)
                key="${1#--}"
                key="${key%%=*}"
                value="${1#*=}"
                parsed_args["$key"]="$value"
                ;;
            --*)
                key="${1#--}"
                if [[ $# -gt 1 && ! $2 =~ ^- ]]; then
                    parsed_args["$key"]="$2"
                    shift
                else
                    parsed_args["$key"]="true"
                fi
                ;;
            -*)
                key="${1#-}"
                if [[ $# -gt 1 && ! $2 =~ ^- ]]; then
                    parsed_args["$key"]="$2"
                    shift
                else
                    parsed_args["$key"]="true"
                fi
                ;;
            *)
                parsed_args["_positional"]="${parsed_args["_positional"]} $1"
                ;;
        esac
        shift
    done
}

# ============================================================================
# Module: 03.core/registry.sh
# ============================================================================

# Register commands and build group index
register_command() {
    local name="$1"
    local description="$2"
    local usage="$3"
    local example="$4"
    local function_name="$5"

    COMMANDS["$name"]="$function_name"
    COMMAND_DESCRIPTIONS["$name"]="$description"
    COMMAND_USAGE["$name"]="$usage"
    COMMAND_EXAMPLES["$name"]="$example"

    # Build command groups index
    if [[ "$name" == *:* ]]; then
        local group="${name%%:*}"
        COMMAND_GROUPS["$group"]+="$name "
    fi
}

# Only parse and register plugin commands
auto_register_plugin_commands() {
    local file="$1"
    local -a lines=()
    local func=""
    local cmd=""
    local desc=""

    mapfile -t lines < "$file"

    for i in "${!lines[@]}"; do
        local line="${lines[$i]}"
        if [[ "$line" =~ ^[[:space:]]*cmd_([a-zA-Z0-9_]+)[[:space:]]*\(\)[[:space:]]*\{ ]]; then
            func="${BASH_REMATCH[0]}"
            local raw_name="${BASH_REMATCH[1]}"
            cmd="${raw_name//_/:}"

            # Check uniqueness
            if [[ -n "${PLUGIN_COMMANDS[$cmd]:-}" || -n "${COMMANDS[$cmd]:-}" ]]; then
                warning "Duplicate command: $cmd (skipped)"
                continue
            fi

            # Description from comment above
            desc=""
            for ((j=i-1; j>=0; j--)); do
                local prev="${lines[$j]}"
                [[ -z "${prev// }" ]] && continue
                if [[ "$prev" =~ ^[[:space:]]*#(.*) ]]; then
                    local comment="${BASH_REMATCH[1]}"
                    desc="$(echo "$comment" | sed 's/\[.*//;s/^[[:space:]]*//;s/[[:space:]]*$//')"
                    if [[ "$comment" =~ \[(.*)\] ]]; then
                        COMMAND_TAGS["$cmd"]="$(echo "${BASH_REMATCH[1]}" | sed 's/,/ /g' | xargs -n1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
                    fi
                fi
                break
            done

            register_command "$cmd" "${desc:-No description}" "" "" "cmd_${raw_name}"
            PLUGIN_COMMANDS["$cmd"]="$file:cmd_${raw_name}"

            # Generate and register alias
            local alias
            alias="$(generate_alias "$cmd")"
            if [[ -z "${COMMANDS[$alias]:-}" && -z "${PLUGIN_COMMANDS[$alias]:-}" && -z "${COMMAND_ALIASES[$alias]:-}" ]]; then
                COMMANDS["$alias"]="cmd_${raw_name}"
                PLUGIN_COMMANDS["$alias"]="$file:cmd_${raw_name}"
                COMMAND_ALIASES["$alias"]="$cmd"
            fi
        fi
    done
}

auto_register_commands() {
    local file="${1:-${BASH_SOURCE[0]}}"
    local -a lines=()
    local func=""
    local cmd=""
    local desc=""

    mapfile -t lines < "$file"

    for i in "${!lines[@]}"; do
        local line="${lines[$i]}"

        # Match cmd_ functions (allow spaces and both function styles)
        if [[ "$line" =~ ^[[:space:]]*cmd_([a-zA-Z0-9_]+)[[:space:]]*\(\)[[:space:]]*\{ ]]; then
            func="${BASH_REMATCH[0]}"
            local raw_name="${BASH_REMATCH[1]}"
            cmd="${raw_name//_/:}"

            # Look for a description comment directly above (skip blank lines)
            desc=""
            for ((j=i-1; j>=0; j--)); do
                local prev="${lines[$j]}"
                [[ -z "${prev// }" ]] && continue
                if [[ "$prev" =~ ^[[:space:]]*#(.*) ]]; then
                    desc="$(echo "${BASH_REMATCH[1]}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
                fi
                break
            done

            register_command "$cmd" "${desc:-No description}" "" "" "cmd_${raw_name}"
        fi
    done
}

# ============================================================================
# Module: 03.core/loader.sh
# ============================================================================

# Generic item registration
# Parameters:
#   $1: type ("command" or "test")
#   $2: directory to scan
#   $3: function prefix ("cmd_" or "test_")
#   $4: storage array name for items (e.g., "PLUGIN_COMMANDS" or "TESTS")
register_items() {
    local item_type="$1"
    local dir="$2"
    local prefix="$3"
    local -n item_storage="$4"
    local script_dir
    script_dir="$(get_script_dir)"

    if [[ ! -d "$dir" ]]; then
        debug "$item_type directory $dir does not exist"
        return
    fi

    for file in "$dir"/*.sh; do
        if [[ ! -f "$file" ]]; then
            continue
        fi

        local -a lines=()
        mapfile -t lines < "$file"

        for i in "${!lines[@]}"; do
            local line="${lines[$i]}"
            if [[ "$line" =~ ^[[:space:]]*${prefix}([a-zA-Z0-9_]+)[[:space:]]*\(\)[[:space:]]*\{ ]]; then
                local raw_name="${BASH_REMATCH[1]}"
                local item_name="${raw_name//_/:}"

                # Check for duplicates
                if [[ "$item_type" == "command" && ( -n "${COMMANDS[$item_name]:-}" || -n "${PLUGIN_COMMANDS[$item_name]:-}" ) ]]; then
                    warning "Duplicate $item_type: $item_name (skipped)"
                    continue
                fi
                if [[ "$item_type" == "test" && -n "${item_storage[$item_name]:-}" ]]; then
                    warning "Duplicate $item_type: $item_name (skipped)"
                    continue
                fi

                # Extract description and tags
                local desc=""
                local tags=""
                for ((j=i-1; j>=0; j--)); do
                    local prev="${lines[$j]}"
                    [[ -z "${prev// }" ]] && continue
                    if [[ "$prev" =~ ^[[:space:]]*#(.*) ]]; then
                        local comment="${BASH_REMATCH[1]}"
                        desc="$(echo "$comment" | sed 's/\[.*//;s/^[[:space:]]*//;s/[[:space:]]*$//')"
                        if [[ "$comment" =~ \[(.*)\] ]]; then
                            tags="$(echo "${BASH_REMATCH[1]}" | sed 's/,/ /g' | xargs -n1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
                        fi
                    fi
                    break
                done

                if [[ "$item_type" == "command" ]]; then
                    # Register command
                    register_command "$item_name" "${desc:-No description}" "" "" "${prefix}${raw_name}"
                    item_storage["$item_name"]="$file:${prefix}${raw_name}"

                    # Generate and register alias
                    local alias
                    alias="$(generate_alias "$item_name")"
                    if [[ -z "${COMMANDS[$alias]:-}" && -z "${PLUGIN_COMMANDS[$alias]:-}" && -z "${COMMAND_ALIASES[$alias]:-}" ]]; then
                        COMMANDS["$alias"]="${prefix}${raw_name}"
                        item_storage["$alias"]="$file:${prefix}${raw_name}"
                        COMMAND_ALIASES["$alias"]="$item_name"
                    fi
                else
                    # Register test
                    item_storage["$item_name"]="$file:${prefix}${raw_name}"
                    [[ -n "$desc" ]] && TEST_DESCRIPTIONS["$item_name"]="$desc"
                    [[ -n "$tags" ]] && TEST_TAGS["$item_name"]="$tags"
                fi
            fi
        done
    done
}

# Get project root directory (handles being in dist/ subdirectory)
get_project_root() {
    local script_dir
    script_dir="$(get_script_dir)"

    # If we're in dist/, go up one level
    if [[ "$(basename "$script_dir")" == "dist" ]]; then
        script_dir="$(dirname "$script_dir")"
    fi

    echo "$script_dir"
}

# Command autoloader
autoload_commands() {
    local project_root
    project_root="$(get_project_root)"
    local command_dirs=(
        "$project_root/commands"
    )

    for dir in "${command_dirs[@]}"; do
        register_items "command" "$dir" "cmd_" PLUGIN_COMMANDS
    done
}

load_tests() {
    local project_root
    project_root="$(get_project_root)"
    local test_dir="$project_root/tests"
    TESTS=()
    TEST_DESCRIPTIONS=()
    TEST_TAGS=()
    register_items "test" "$test_dir" "test_" TESTS
}

# ============================================================================
# Module: 04.commands/help.sh
# ============================================================================

# Version display
show_version() {
    echo -e "${BOLD}$CLI_NAME${NC} version ${GREEN}$CLI_VERSION${NC}"
}

# Show commands in a specific group
show_group_commands() {
    local group="$1"
    local commands="${COMMAND_GROUPS[$group]:-}"

    if [[ -z "$commands" ]]; then
        error "No commands found in group: $group"
        return 1
    fi

    echo -e "${YELLOW}Available commands for the '${group}' namespace:${NC}\n"

    for cmd in $commands; do
        local desc="${COMMAND_DESCRIPTIONS[$cmd]:-No description}"
        local tag_str=""
        if [[ -n "${COMMAND_TAGS[$cmd]:-}" ]]; then
            for tag in ${COMMAND_TAGS[$cmd]}; do
                tag_str+=" [$tag]"
            done
        fi
        printf "  ${GREEN}%-35s${NC} %s%s\n" "$cmd" "$desc" "$tag_str"
    done

    echo -e "\n${BOLD}Usage:${NC} $CLI_NAME ${YELLOW}<command>${NC} [arguments] [options]"
    echo -e "${BOLD}Example:${NC} $CLI_NAME ${GREEN}${commands%% *}${NC}"
}

# Help system
show_help() {
    local command="${1:-}"
    if [[ -n "$command" && -n "${COMMANDS[$command]:-}" ]]; then
        show_command_help "$command"
    elif [[ -n "$command" && -n "${COMMAND_GROUPS[$command]:-}" ]]; then
        show_group_commands "$command"
    else
        show_general_help
    fi
}

# Print grouped command list
print_command_list() {
    declare -A groups
    local no_prefix=""

    for cmd in "${!COMMANDS[@]}"; do
        if [[ -n "${COMMAND_ALIASES[$cmd]:-}" ]]; then continue; fi
        if [[ "$cmd" == *:* ]]; then
            prefix="${cmd%%:*}"
            groups["$prefix"]+="$cmd|${COMMAND_DESCRIPTIONS[$cmd]:-}|${COMMAND_TAGS[$cmd]:-}"$'\n'
        else
            no_prefix+="$cmd|${COMMAND_DESCRIPTIONS[$cmd]:-}|${COMMAND_TAGS[$cmd]:-}"$'\n'
        fi
    done

    # Print commands without prefix first
    if [[ -n "$no_prefix" ]]; then
        while IFS= read -r row; do
            [[ -z "$row" ]] && continue
            IFS='|' read -r cmd desc tags <<< "$row"
            local tag_str=""
            if [[ -n "$tags" ]]; then
                for tag in $tags; do
                    tag_str+=" [$tag]"
                done
            fi
            printf "  ${GREEN}%-35s${NC} %s%s\n" "$cmd" "$desc" "$tag_str"
        done <<< "$(echo "$no_prefix" | sort)"
    fi

    # Print grouped commands
    for prefix in $(printf '%s\n' "${!groups[@]}" | sort); do
        echo -e "${YELLOW}$prefix${NC}"
        while IFS= read -r row; do
            [[ -z "$row" ]] && continue
            IFS='|' read -r cmd desc tags <<< "$row"
            local tag_str=""
            if [[ -n "$tags" ]]; then
                for tag in $tags; do
                    tag_str+=" [$tag]"
                done
            fi
            printf "  ${GREEN}%-35s${NC} %s%s\n" "$cmd" "$desc" "$tag_str"
        done <<< "$(echo "${groups[$prefix]}" | sort)"
    done
}

show_general_help() {
    echo -e "${WHITE}$CLI_DESCRIPTION${NC}\n"
    echo -e "${YELLOW}Usage:${NC}"
    echo -e "  $CLI_NAME ${YELLOW}<command>${NC} [arguments] [options]"
    echo -e "  $CLI_NAME ${YELLOW}<group>${NC} Show commands in group\n"

    echo -e "${YELLOW}Options:${NC}"
    cat <<EOF
  -h, --help            Display help for the given command. When no command is given display help for the list command
      --silent          Do not output any message
  -q, --quiet           Only errors are displayed. All other output is suppressed
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
EOF

    echo
    echo -e "${YELLOW}Available commands:${NC}"
    print_command_list
}

show_command_help() {
    local command="$1"
    echo -e "${BOLD}COMMAND:${NC} ${GREEN}$command${NC}"
    echo -e "${BOLD}DESCRIPTION:${NC}\n  ${COMMAND_DESCRIPTIONS[$command]}"
    echo -e "${BOLD}USAGE:${NC}\n  $CLI_NAME $command ${COMMAND_USAGE[$command]}"
    if [[ -n "${COMMAND_EXAMPLES[$command]}" ]]; then
        echo -e "${BOLD}EXAMPLE:${NC}\n  $CLI_NAME $command ${COMMAND_EXAMPLES[$command]}"
    fi
}

cmd_help() {
    local -A args
    parse_arguments args "$@"
    local command="${args[_positional]:-}"
    show_help "$command"
}

# Manual registration of help command
register_command "help" "Show help for a command" "[command]" "help demo" "cmd_help"

# ============================================================================
# Module: 04.commands/list.sh
# ============================================================================

cmd_list() {
    local -A args
    parse_arguments args "$@"
    local filter="${args[_positional]:-}"
    filter="$(echo "$filter" | xargs)" # trim spaces
    local tag_filter="${args[tag]:-}"

    if [[ -n "$tag_filter" ]]; then
        echo -e "${YELLOW}Available commands with tag \"${tag_filter}\":${NC}"
        print_command_list | grep --color=never "\[${tag_filter}\]"
    elif [[ -n "$filter" ]]; then
        echo -e "${YELLOW}Available commands matching \"${filter}\":${NC}"
        print_command_list | grep -i --color=never "$filter"
    else
        echo -e "${YELLOW}Available commands:${NC}"
        print_command_list
    fi
}

# Manual registration of list command
register_command "list" "List all available commands" "" "" "cmd_list"

# ============================================================================
# Module: 04.commands/demo.sh
# ============================================================================

cmd_demo() {
    local -A args
    parse_arguments args "$@"
    info "Starting demo..."
    echo -e "\n${BOLD}Progress Bar Demo:${NC}"
    for i in {1..20}; do
        show_progress "$i" 20
        sleep 0.05
    done
    echo -e "\n${BOLD}Table Demo:${NC}"
    local demo_headers=("Name" "Age" "City")
    local demo_rows=("Alice|25|New York" "Bob|30|London" "Charlie|35|Tokyo")
    print_table demo_headers demo_rows
}

# Manual registration of demo command
register_command "demo" "Show demo of progress bar and table" "" "" "cmd_demo"

# ============================================================================
# Module: 04.commands/test.sh
# ============================================================================

cmd_test() {
    local -A args
    parse_arguments args "$@"
    local test_name="${args[_positional]:-}"
    test_name="$(echo "$test_name" | xargs)"

    # Set project root for tests
    export PROJECT_ROOT="$(get_project_root)"

    echo -e "${BOLD}Starting CLI Framework Tests${NC}\n"

    load_tests

    if [[ ${#TESTS[@]} -eq 0 ]]; then
        error "No tests found"
        exit 1
    fi

    local tests_to_run=()
    if [[ -n "$test_name" ]]; then
        if [[ -n "${TESTS[$test_name]:-}" ]]; then
            tests_to_run+=("$test_name")
        else
            error "Test $test_name not found"
            exit 1
        fi
    else
        for test in "${!TESTS[@]}"; do
            tests_to_run+=("$test")
        done
        # Sort for consistent order
        readarray -t tests_to_run < <(printf '%s\n' "${tests_to_run[@]}" | sort)
    fi

    for test_name in "${tests_to_run[@]}"; do
        local info="${TESTS[$test_name]}"
        local file="${info%%:*}"
        local func="${info##*:}"
        line
        test_info "Running test: $test_name${TEST_DESCRIPTIONS[$test_name]:+ - ${TEST_DESCRIPTIONS[$test_name]}}"
        line
        # shellcheck source=/dev/null
        source "$file"
        "$func"
    done

    echo
    echo -e "${BOLD}Test Results:${NC}"
    echo -e "  Total Tests: ${BLUE}$TESTS_TOTAL${NC}"
    echo -e "  Passed: ${GREEN}$TESTS_PASSED${NC}"
    echo -e "  Failed: ${RED}$TESTS_FAILED${NC}"
    if [[ $TESTS_FAILED -eq 0 ]]; then
        echo -e "\n${GREEN}${BOLD}All tests passed!${NC}"
        exit 0
    else
        echo -e "\n${RED}${BOLD}Some tests failed!${NC}"
        exit 1
    fi
}

# Manual registration of test command
register_command "test" "Run tests for the CLI framework" "[test_name]" "test basic_commands" "cmd_test"

# ============================================================================
# Module: 05.runner/executor.sh
# ============================================================================

run_cli() {
    local output=""
    local exit_code=0
    local original_dir="$(pwd)"

    cd "$(dirname "${BASH_SOURCE[0]}")" || return 1
    output=$("./$CLI_NAME" "$@" 2>/dev/null) || exit_code=$?
    cd "$original_dir" || return 1

    echo "$output"
    return $exit_code
}

run_cli_with_stderr() {
    local output=""
    local exit_code=0
    local original_dir="$(pwd)"

    cd "$(dirname "${BASH_SOURCE[0]}")" || return 1
    output=$("./$CLI_NAME" "$@" 2>&1) || exit_code=$?
    cd "$original_dir" || return 1

    echo "$output"
    return $exit_code
}

assert_contains() {
    local output="$1"
    local expected="$2"
    local test_name="$3"

    if [[ "$output" == *"$expected"* ]]; then
        test_pass "$test_name"
    else
        test_fail "$test_name - Expected '$expected' in output"
        echo "Actual output: ${output:0:200}..." >&2
    fi
}

assert_not_contains() {
    local output="$1"
    local unexpected="$2"
    local test_name="$3"

    if [[ "$output" != *"$unexpected"* ]]; then
        test_pass "$test_name"
    else
        test_fail "$test_name - Did not expect '$unexpected' in output"
        echo "Actual output contains forbidden string." >&2
    fi
}

assert_equals() {
    local expected="$1"
    local actual="$2"
    local test_name="$3"

    if [[ "$expected" == "$actual" ]]; then
        test_pass "$test_name"
    else
        test_fail "$test_name - Expected '$expected', got '$actual'"
    fi
}

assert_exit_code() {
    local expected_code="$1"
    local actual_code="$2"
    local test_name="$3"

    if [[ "$actual_code" -eq "$expected_code" ]]; then
        test_pass "$test_name"
    else
        test_fail "$test_name - Expected exit code $expected_code, got $actual_code"
    fi
}

execute_plugin_command() {
    local cmd="$1"
    shift
    local info="${PLUGIN_COMMANDS[$cmd]}"
    local file="${info%%:*}"
    local func="${info##*:}"

    # shellcheck source=/dev/null
    source "$file"
    "$func" "$@"
}

# ============================================================================
# Module: 05.runner/main.sh
# ============================================================================

main() {
    # Load environment variables from .env files
    local project_root
    project_root=$(get_env_project_root)
    load_env "$project_root"

    autoload_commands

    local command="${1:-help}"
    case "$command" in
        "--version"|"-V") show_version; exit 0 ;;
    esac

    # Check if it's a group shortcut
    if [[ -n "${COMMAND_GROUPS[$command]:-}" ]]; then
        show_group_commands "$command"
        exit 0
    fi

    if [[ -n "${PLUGIN_COMMANDS[$command]:-}" ]]; then
        shift
        execute_plugin_command "$command" "$@"
        exit $?
    fi

    if [[ -z "${COMMANDS[$command]:-}" ]]; then
        error "Unknown command: $command"
        show_general_help
        exit 1
    fi

    shift
    local func_name="${COMMANDS[$command]}"
    "$func_name" "$@"
}

# ============================================================================
# Module: 99.bootstrap/init.sh
# ============================================================================

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [ $# -eq 0 ]; then
        main help
    else
        main "$@"
    fi
fi
